### ISSUE TITLE
dial tcp: lookup xxxx on 127.0.0.11:53: no such host

### ISSUE THREAD

**Issue by umarsyarif** [krakendio/krakend-ce#514]
**Environment info:**

* KrakenD version: Version: 2.0.4
* System info: Linux 5.10.76-linuxkit x86_64
* Hardware specs: Apple M1 chip 8-Core CPU
* Backend technology: PHP
* Additional environment information:

**Describe what are you trying to do**:
I'm trying to run Krakend with docker but keep getting this error when try to hit the endpoint. I'm not using any VPN.

**Your docker-compose file**:

```
version: '3'
services:
    api-gateway:
        image: devopsfaith/krakend:2.0.4
        volumes:
        - ./src/api-gateway:/etc/krakend
        ports:
        # - "1234:1234"
        - "8080:8080"
        # - "8090:8090"
        command: ["run", "-d", "-c", "/etc/krakend/krakend-config.json"]
        depends_on:
        - registration-service
        - registrant-service
        - announcement-service
        - mail-service
    registration-service:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-8001}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - './src/registration-service:/var/www/html'
        networks:
            - sail
        depends_on:
            - registration-db
            - redis
    registrant-service:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-8002}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - './src/registrant-service:/var/www/html'
        networks:
            - sail
        depends_on:
            - registrant-db
            - redis
    announcement-service:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-8003}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - './src/announcement-service:/var/www/html'
        networks:
            - sail
        depends_on:
            - announcement-db
            - redis
    mail-service:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-8004}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - './src/mail-service:/var/www/html'
        networks:
            - sail
        depends_on:
            - redis
    account-service:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-8005}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - './src/account-service:/var/www/html'
        networks:
            - sail
        depends_on:
            - account-db
            - redis
    registration-db:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3316}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD_REGISTRATION}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE_REGISTRATION}'
            MYSQL_USER: '${DB_USERNAME_REGISTRATION}'
            MYSQL_PASSWORD: '${DB_PASSWORD_REGISTRATION}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - './src/registration-service/sail-mysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD_REGISTRATION}"]
            retries: 3
            timeout: 5s
    registrant-db:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3317}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD_REGISTRANT}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE_REGISTRANT}'
            MYSQL_USER: '${DB_USERNAME_REGISTRANT}'
            MYSQL_PASSWORD: '${DB_PASSWORD_REGISTRANT}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - './src/registrant-service/sail-mysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD_REGISTRANT}"]
            retries: 3
            timeout: 5s
    announcement-db:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3318}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD_ANNOUNCEMENT}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE_ANNOUNCEMENT}'
            MYSQL_USER: '${DB_USERNAME_ANNOUNCEMENT}'
            MYSQL_PASSWORD: '${DB_PASSWORD_ANNOUNCEMENT}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - './src/announcement-service/sail-mysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD_ANNOUNCEMENT}"]
            retries: 3
            timeout: 5s
    account-db:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3319}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD_ACCOUNT}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE_ACCOUNT}'
            MYSQL_USER: '${DB_USERNAME_ACCOUNT}'
            MYSQL_PASSWORD: '${DB_PASSWORD_ACCOUNT}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - './src/account-service/sail-mysql:/var/lib/mysql'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD_ACCOUNT}"]
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local

```
**Your configuration file**:

```json
{
  "$schema": "https://www.krakend.io/schema/v3.json",
  "version": 3,
  "name": "PPDB - API Gateway",
  "timeout": "3000ms",
  "cache_ttl": "300s",
  "output_encoding": "json",
  "port": 8080,
  "endpoints": [
    {
      "endpoint": "/v1/registration/period",
      "method": "GET",
      "output_encoding": "json",
      "backend": [
        {
          "url_pattern": "/api/period",
          "encoding": "json",
          "sd": "static",
          "method": "GET",
          "disable_host_sanitize": true,
          "host": [
            "http://registration-service:80"
          ]
        }
      ]
    },
    {
      "endpoint": "/v1/registration/period",
      "method": "POST",
      "output_encoding": "json",
      "backend": [
        {
          "url_pattern": "/api/period",
          "encoding": "json",
          "sd": "static",
          "method": "POST",
          "disable_host_sanitize": false,
          "host": [
            "http://registration-service:80"
          ]
        }
      ],
      "extra_config": {
        "auth/validator": {
          "alg": "HS256",
          "jwk_url": "MY_JWK_URL/jwks.json"
        }
      },
      "input_headers": [
        "Authorization",
        "Content-Type",
        "Accept"
      ]
    },
    {
      "endpoint": "/v1/registration/period/{id}",
      "method": "PUT",
      "output_encoding": "json",
      "backend": [
        {
          "url_pattern": "/api/period/{id}",
          "encoding": "json",
          "sd": "static",
          "method": "PUT",
          "disable_host_sanitize": false,
          "host": [
            "http://registration-service:80"
          ]
        }
      ],
      "extra_config": {
        "auth/validator": {
          "alg": "HS256",
          "jwk_url": "MY_JWK_URL/jwks.json"
        }
      },
      "input_headers": [
        "Authorization",
        "Content-Type",
        "Accept"
      ]
    }
  ],
  "extra_config": {
    "security/cors": {
      "allow_origins": [
        "*"
      ],
      "expose_headers": [
        "Content-Length"
      ],
      "max_age": "12h",
      "allow_methods": [
        "GET",
        "POST",
        "PUT",
        "DELETE"
      ],
      "allow_headers": [
        "Authorization",
        "Content-Type",
        "Accept",
        "x-access-token"
      ],
      "allow_credentials": true
    }
  }
}
```

**Configuration check output**:
Result of `krakend check -dtc krakend.json --lint` command

```
Global settings
	Name: PPDB - API Gateway
	Port: 8080
1 global component configuration(s):
- security/cors
3 API endpoint(s):
	- GET /v1/registration/period
	Timeout: 3s
	Connecting to 1 backend(s):
		[+] GET /api/period
		Timeout: 3s
		Hosts: [http://registration-service:80]

	- POST /v1/registration/period
	Timeout: 3s
	1 endpoint component configuration(s):
	- auth/validator
	Connecting to 1 backend(s):
		[+] POST /api/period
		Timeout: 3s
		Hosts: [http://registration-service:80]

	- PUT /v1/registration/period/:id
	Timeout: 3s
	1 endpoint component configuration(s):
	- auth/validator
	Connecting to 1 backend(s):
		[+] PUT /api/period/{{.Id}}
		Timeout: 3s
		Hosts: [http://registration-service:80]

0 async agent(s):
Syntax OK!
```

**Commands used:**
How did you start the software?
```
krakend run -d -c krakend.json
```

**Logs:**
```
2022/06/22 17:09:34 KRAKEND ERROR: [ENDPOINT: /v1/registration/period] Get "http://registration-service:80/api/period": dial tcp: lookup registration-service on 127.0.0.11:53: no such host
```

**Additional comments:**
