### ISSUE TITLE
connection refused

### ISSUE THREAD

**Issue by marvinhosea** [krakendio/krakend-ce#583]
**Environment info:**

* KrakenD version: Version: 2.0.4
* System info: docker
* Hardware specs: docker
* Backend technology: Go

**Describe what are you trying to do**:
I am getting started and after successfully writing a krakend config file and running it against the backend I got "connection refused" yet the backend is up and running.

**Your configuration file**:

```yaml
version: 3
name: Pesa
timeout: 3000ms
output_encoding: json
extra_config:
  security/cors:
    allow_origins:
      - "*"
    expose_headers:
      - "Content-Length"
    max_age: 12h
    allow_headers:
      - "Content-Type"
      - "Accept"
      - "Authorization"
    allow_methods:
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
      - "GET"
      - "PATCH"
endpoints:
  - endpoint: '/models'
    method: GET
    backend:
      - url_pattern: '/v1/models'
        method: GET
        host:
          - "http://127.0.0.1:9001"
  - endpoint: /auth/login
    method: POST
    backend:
      - url_pattern: '/v1/auth/login'
        method: POST
        host:
          - "http://127.0.0.1:9001"
```

**Configuration check output**:
Result of `krakend check -dtc krakend.json --lint` command

```
Global settings
	Name: Pesa
	Port: 8080
1 global component configuration(s):
- security/cors
2 API endpoint(s):
	- GET /models
	Timeout: 3s
	Connecting to 1 backend(s):
		[+] GET /v1/models
		Timeout: 3s
		Hosts: [http://127.0.0.1:9001]

	- POST /auth/login
	Timeout: 3s
	Connecting to 1 backend(s):
		[+] POST /v1/auth/login
		Timeout: 3s
		Hosts: [http://127.0.0.1:9001]

0 async agent(s):
Syntax OK!
```

**Commands used:**
How did you start the software?
```

krakend:
    image: devopsfaith/krakend:watch
    ports:
      - "9005:8080"
    command: ["run", "-d", "-c", "/etc/krakend/krakend.yaml"]
    volumes:
      - ./config/krakend:/etc/krakend-d
```

**Logs:**
pesa-krakend-1  | [00] 2022/09/24 17:11:15 KRAKEND ERROR: [ENDPOINT: /models] Get "http://127.0.0.1:9001/v1/models": dial tcp 127.0.0.1:9001: connect: connection refused
pesa-krakend-1  | [00] [GIN] 2022/09/24 - 17:11:15 | 500 |    2.984083ms |      172.21.0.1 | GET      "/models"

**Additional comments:**
