### ISSUE TITLE
Status Code 200 from api always get timout 

### ISSUE THREAD

**Issue by MaxwellPereira** [krakendio/krakend-ce#585]
**Environment info:**

* KrakenD version: Version: 2.0.6
* System info: Docker
* Hardware specs: 
* Backend technology: Node

**Describe what are you trying to do**:
O trying to configure krakend to integrate microservices, and when the api return HTTP/200, the krakend always get timout with HTTP/500, but when api return some error the krakend return correct, same as the api. 

**Your configuration file**:

```json
{
    "$schema": "https://www.krakend.io/schema/v3.json",
    "version": 3,
    "name": "KrakenD - API Gateway",
    "port": 8080,
    "host": [
        "http://localhost:8080"
    ],
    "extra_config": {
        "security/cors": {
            "allow_origins": [
                "*"
            ],
            "expose_headers": [
                "Content-Length"
            ],
            "max_age": "12h",
            "allow_methods": [
                "GET",
                "HEAD",
                "POST",
                "PUT",
                "DELETE"
            ],
            "allow_headers": ["Origin", "Authorization", "Content-Type"]
        },
        "plugin/http-server": {
            "name": [
                "static-filesystem"
            ],
            "static-filesystem": {
                "prefix": "/media/assets",
                "path": "/var/www/static"
            }
        }
    },
    "timeout": "30000ms",
    "cache_ttl": "3000s",
    "output_encoding": "json",
    "disable_rest": true,
    "sequential_start": true,
    "endpoints": [{
            "endpoint": "/sessions",
            "timeout": "10s",
            "input_headers": ["Content-Type"],
            "method": "POST",
            "backend": [{
                "host": [
                    "10.1.8.115:1000"
                ],
                "method": "POST",
                "url_pattern": "/sessions"
            }]
        }
    ],
    "plugin": {
        "pattern": ".so",
        "folder": "/opt/krakend/plugins/"
    }
}
```

**Configuration check output**:
Result of `krakend check -dtc krakend.json --lint` command

```
Global settings
        Name: KrakenD - API Gateway
        Port: 8080
        Default backend hosts: [http://localhost:8080]
        Folder: /opt/krakend/plugins/
        Pattern: .so
2 global component configuration(s):
- plugin/http-server
- security/cors
5 API endpoint(s):
        - POST /sessions
        Timeout: 10s
        Connecting to 1 backend(s):
                [+] POST /sessions
                Timeout: 10s
                Hosts: [http://10.1.8.115:1000]

        - GET /tickets
        Timeout: 10s
        Connecting to 1 backend(s):
                [+] GET /tickets
                Timeout: 10s
                Hosts: [http://10.1.8.115:1002]
                1 backend component configuration(s):
                - backend/http

        - POST /test2
        Timeout: 10s
        Connecting to 1 backend(s):
                [+] POST /sessions
                Timeout: 10s
                Hosts: [http://localhost:3001]
                1 backend component configuration(s):
                - backend/http

        - GET /test2
        Timeout: 30s
        Connecting to 1 backend(s):
                [+] GET /sessions
                Timeout: 30s
                Hosts: [http://localhost:3001]

        - GET /test
        Timeout: 30s
        Connecting to 1 backend(s):
                [+] GET /hello-world/hello/world
                Timeout: 30s
                Hosts: [https://sandbox.api.service.nhs.uk]

0 async agent(s):
Syntax OK!
```

**Commands used:**
How did you start the software?
```
version: "3.6"

networks:
  krakend-network:
    driver: bridge

services:
  krakend_ce:
    # The :watch image restarts the service automatically when the configuration files change.
    # Do not use this image in production, it's meant to speed up your testing and development.
    image: devopsfaith/krakend:watch
    volumes:
      - ./config/krakend:/etc/krakend
    ports:
      - "1234:1234"
      - "8080:8080"
      - "8090:8090"
    command: ["run", "-d", "-c", "/etc/krakend/krakend.json"]
```

**Logs:**
Logs you saw in the console and debugging information

**Additional comments:**
