### ISSUE TITLE
krakend image(latest 2.1.3) fails to start: su-exec: setgroups: Operation not permitted

### ISSUE THREAD

**Issue by javiermorant** [krakendio/krakend-ce#634]
I got an error deploying krakend in a kubernetes cluster
Logs from the error are: `su-exec: setgroups: Operation not permitted`

Docker file:
```
FROM golang:1.17-alpine as build

RUN go get github.com/krakendio/krakend-ce/v2/cmd/krakend-integration

FROM devopsfaith/krakend

COPY --from=build /go/bin/krakend-integration /usr/bin/

COPY conf/krakend.json .

EXPOSE 8090 8091
```

Modifying the docker file to use previous version 2.1.2 -> `FROM devopsfaith/krakend:2.1.2` Fixes the issue .

Taking a look to the changes between those builds I noticed some changes in the docker library project that are maybe related. https://github.com/krakendio/docker-library/commits/main

Is there any additional step to add to the configuration to adapt to the last version?

Thanks!

**Comment by taik0** [comment]
Looks like you are running the container as an unprivileged user. The new entrypoint executes KrakenD with `su-exec`.

**Comment by rschumm** [comment]
I have the same issue by just running `devopsfaith/krakend` on an OpenShift cluster.   
Is this the Dockerfile? https://github.com/krakendio/krakend-ce/blob/master/Dockerfile 

And: does the container really needs a privileged user - or am I confused?

**Comment by reytech-dev** [comment]
hey there,
I read the new [entrypoint.sh](https://github.com/krakendio/docker-library/blob/master/2.1.4/docker-entrypoint.sh).
I'm not sure if I understood it right:
According to the comment above the "su-exec" command, the container needs to be started with a privileged user to be able to "drop to a non-root user". 
Wouldn't it be more convenient to add a check for the uid of the current user that is used in the container and starts the entrypoint instead of always assuming it gets executed by a privileged user? It would make it easier to use the image in environments without privileged users.

Example pod:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: krakend
spec:
  securityContext:
    runAsUser: 1000
  containers:
  - name: krakend
    image: "devopsfaith/krakend:2.1.3"
    imagePullPolicy: IfNotPresent
    args: [ "run", "-c", "/etc/krakend/krakend.json", "-p", "8080", ">/dev/null", "2>&1" ]
    securityContext:
      allowPrivilegeEscalation: false
``

Example docker-entrypoint.sh:
```sh
#!/bin/sh
set -e

commandRun="run"
commandVersion="version"
commandCheck="check"
commandPlugin="check-plugin"
commandHelp="help"
commandValidate="validate"

# this if will check if the first argument is a flag
# but only works if all arguments require a hyphenated flag
# -v; -SL; -f arg; Also check if the first argument is any
# of the KrakenD commands
if [ "$#" -eq 0 ] || [ "${1#-}" != "$1" ] ||
   [ "$1" = "${commandRun}" ] || 
   [ "$1" = "${commandVersion}" ] || 
   [ "$1" = "${commandCheck}" ] || 
   [ "$1" = "${commandPlugin}" ] ||
   [ "$1" = "${commandValidate}" ] ||
   [ "$1" = "${commandHelp}" ]; then
    set -- krakend "$@"
fi

# check for the expected command
if [ "$1" = 'krakend' ]; then
    # krakend user has uid 1000
    # https://kubernetes.io/docs/tasks/configure-pod-container/security-context/
    # runAsUser: 1000
    if [ "$(id -u)" = 1000 ]; then
        exec "$@"    
    else
        # use gosu (or su-exec) to drop to a non-root user
        exec su-exec krakend "$@"
    fi
fi

# else default to run whatever the user wanted like "bash" or "sh"
exec "$@"
```
Please let me know, if I miss on something or misunderstood the purpose of the usage of su-exec.
