### ISSUE TITLE
Cannot use original header on Response Modifier Plugin (I can't modify the backend)

### ISSUE THREAD

**Issue by rafaeljourdan** [krakendio/krakend-ce#643]
**Environment info:**

* KrakenD version: Version: 2.1.3
* System info: docker
* Hardware specs: Lenovo ThinkPad E15 Gen 2, 32GB ram
* Backend technology: Node
* Additional environment information:

**Describe what are you trying to do**:
Hello

I want to use the **request.Header** on **Response Modifier plugin**  without changing anything on the backend (I am not allowed to do it)

For example, the API Gateway receives data from the original request on **Headers** and the Request Modifier Plugin XPTO or the auth/validator treats the information and attaches some data to a new Header ("X-Username" for example)

I want to get the **X-Username** header on the **Response Modifier Plugin** alongside the response body from the backend. The response needs to be encrypted using data present on the original request.headers.

Is it possible?

Many thanks! 

**Your configuration file**:

```json
{
  {
  "$schema": "https://www.krakend.io/schema/v3.json",
  "version": 3,
  "host": "http://localhost:8081",
  "port": "8081",

  "name": "KrakenD ",
  "extra_config": {
    "router": {
      "return_error_msg": true
    },
    "security/cors": {
      "allow_methods": ["GET", "POST", "PUT", "PATCH", "DELETE"]
    }
  },
  "output_encoding": "json",
  "timeout": "2000ms",
  "cache_ttl": "300s",
  "host_v2_1": "v2.1",
  "debug_endpoint": true,
  "plugin": {
    "pattern": ".so",
    "folder": "/etc/krakend/plugins/.bin/"
  },

  "endpoints": [
    {
      "@comment": "Auth: generate token",
      "endpoint": "v2.1/auth/token",
      "method": "POST",
      "backend": [
        {
          "url_pattern": "/oidc/token",
          "host": ["URL_HERE"],
          "method": "POST",
          "encoding": "json",
          "allow": ["access_token", "expires_in", "token_type", "scope"]
        }
      ],
      "output_encoding": "json"
    },
    {
      "endpoint": "v2.1/debug",
      "method": "POST",
      "output_encoding": "json",

      "input_headers": ["Authorization", "Content-Type", "X-Username"],

      "extra_config": {
        "auth/validator": {
          "alg": "RS256",
          "jwk_url": "URL_HERE",
          "cache": true,
          "cache_duration": 600,
          "roles_key": "roles",
          "roles": ["ROLE_SERVICE"],
          "operation_debug": true,
          "propagate_claims": [["username", "X-Username"]]
        }
      },

      "backend": [
        {
          "url_pattern": "/__debug/default",
          "method": "POST",
          "encoding": "json",
          "extra_config": {
            "modifier/martian": {
              "header.Copy": {
                "scope": ["request", "response"],
                "from": "X-Username",
                "to": "X-TEST"
              }
            },
            "plugin/req-resp-modifier": {
              "name": [
                "decryption-payload-plugin",
                "get-entity-plugin",
                "encryption-response-plugin"
              ],
              "decryption-payload-plugin": {
                "HOST_ENTITY_SERVICE": "URL_HERE",
                "HOST_ENCRYPTION_SERVICE": "URL_HERE"
              },
              "encryption-response-plugin": {
                "HOST_ENTITY_SERVICE": "URL_HERE",
                "HOST_ENCRYPTION_SERVICE": "URL_HERE"
              }
            }
          }
        }
      ]
    }
  ]
}

}
```

**Commands used:**
How did you start the software?
```
version: "3"
services:
  krakend:
    container_name: krakend
    image: devopsfaith/krakend:watch
    volumes:
      - .:/etc/krakend
    environment:
      PORT: "8081"
      API_VERSION_2_1: "v2.1"
      HOST_ENTITY_SERVICE: "URL_HERE"
      HOST_ENCRYPTION_SERVICE: "URL_HERE"
      FC_ENABLE: "1"
      FC_SETTINGS: "/etc/krakend/settings"
      FC_TEMPLATES: "/etc/krakend/templates"
      FC_PARTIALS: "/etc/krakend/partials"
      FC_OUT: "/tmp/out.json"
    command:
      ["run", "-d", "-c", "/etc/krakend/krakend.tmpl"]
    ports:
      - 8080:8081
```

**Logs:**
![image](https://user-images.githubusercontent.com/3641909/208498310-c4ad2342-ea40-4f17-84f1-16ad6526b810.png)

**Additional comments:**
